DROP TABLE IF EXISTS set_logs;
DROP TABLE IF EXISTS exercise_logs;
DROP TABLE IF EXISTS cycles;
DROP TABLE IF EXISTS exercises;
DROP TABLE IF EXISTS workouts;
DROP TABLE IF EXISTS plans;
DROP TABLE IF EXISTS users;
